### ISSUE TITLE
Build failure after 2014-12-31 commits

### ISSUE THREAD

**Issue by FabioPedretti** [llvm-mirror/libclc#1]
Apparently it should require llvm 3.6:
https://github.com/llvm-mirror/libclc/commit/9a53500b66544d50b0f42afa4eb0de3b6cdbcb16

However it doesn't fail at configure when using 3.5, but fails later on during compile:
https://launchpadlibrarian.net/193790369/buildlog_ubuntu-trusty-i386.libclc_0~git20141231.1830.0bb35f~gd~t_FAILEDTOBUILD.txt.gz

**Comment by dtzWill** [comment]
Hi @FabioPedretti! Thanks for reporting this and for your interest in LLVM software.

Unfortunately, this isn't where such issues should be reported, it's just a mirror provided for convenience to the community.

The appropriate place for such things is the LLVM Bugzilla: http://llvm.org/bugs/ .

Please report your issues there so they will be seen and handled!

Thanks!

**Comment by FabioPedretti** [comment]
Thanks for the reply, I am closing this issue anyway since I upgraded to llvm-3.6 and cannot reproduce it.
